run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - gci
    - goerr113
    - gofumpt
    - goimports
    - gomnd
    - lll
    - nlreturn
    - stylecheck
    #   - testpackage
    - varnamelen
    #   - wrapcheck
    - wsl
linters-settings:
  funlen:
    lines: 120
issues:
  exclude:
    - "G304" # Potential file inclusion via variable
  exclude-use-default: false
