name: pre-commit

on:
  pull_request:

jobs:
  scan-terraform:
    uses: defenseunicorns/uds-common-workflows/.github/workflows/terraform-scan.yaml@main
    with:
      soft-fail: true
      github-token: $GITHUB_TOKEN
