# On every push to main, run release-please to automatically handle the release process.

name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:

  release-please:
    runs-on: ubuntu-latest
    steps:

      - name: Get token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.NARWHAL_BOT_APP_ID }}
          application_private_key: ${{ secrets.NARWHAL_BOT_SECRET }}

      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          command: manifest
