name: Release Please Merge
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write
  repository-projects: read

jobs:
  release-terraform:
    uses: defenseunicorns/uds-common-workflows/.github/workflows/release-terraform.yml@main
    with:
      command: manifest
      release-type: simple
