name: repo-config

on:
  schedule:
    # daily at 11:00 UTC
    - cron: '0 11 * * *'

jobs:
  repo-config:
    uses: defenseunicorns/delivery-github-actions-workflows/.github/workflows/repo-config.yml@main
    secrets:
      APPLICATION_ID: ${{ secrets.NARWHAL_BOT_APP_ID }}
      APPLICATION_PRIVATE_KEY: ${{ secrets.NARWHAL_BOT_SECRET }}
    with:
      branch: main
      checks: |-
        checks:
          - context: 'e2e-tests'
          - context: 'pre-commit-checks'
